
server:
  port: 1001

   #keytool -genkeypair -alias myalias -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore fileName -validity 3650

   # Enable SSL (HTTPS)
  ssl:
      key-store: ${greenspaces-keystore}
      key-store-password: ${greenspaces-ks-pwd}
      key-store-type: 'PKCS12'
#      key-alias: 'greenspaces-keys'

logging:
  level:
    org:
      springframework:
        security: 'DEBUG'

spring:
  application:
    name: greenspaces

  #establish connection to mysql database
  datasource:
      url: 'jdbc:mysql://localhost:3306/greenspaces'
      username: 'greenspaces'
      password: 'greenspaces'
      driver-class-name: 'com.mysql.cj.jdbc.Driver'
      jpa:
        hibernate:
          ddl-auto: 'update'
          show-sql: true

greenspaces:
  resource-server-details:
    clientID: ${resource-server-clientID}
    secret: ${resource-server-secret}
    introspectionUri: ${resource-server-introspectionUri}
    keySetUri: ${resource-server-keysetUri}





